name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install OpenSSL Development Packages
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Set release tag
      id: set_tag
      run: |
        tag=$(git rev-parse --short=8 ${{ github.sha }})
        echo "tag=${tag}" >> $GITHUB_ENV

    - name: Set up Rust Environment for Linux x86_64
      run: |
        rustup target add x86_64-unknown-linux-gnu

    - name: List Rust Environment Version info
      run: |
        rustup --version
        cargo --version
        rustc --version

    - name: Build for Linux x86-64
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu
        cp target/x86_64-unknown-linux-gnu/release/rust-quicktotp ./quicktotp-linux-x86_64

    - name: Generate Changelog
      run: echo "# Release Notes" > changelog.txt  # Replace this with your actual changelog content

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          changelog.txt
          quicktotp-linux-x86_64
        body_path: changelog.txt
        tag_name: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Set release tag
      id: set_tag
      run: |
        tag=$(git rev-parse --short=8 ${{ github.sha }})
        echo "tag=${tag}" >> $GITHUB_ENV

    - name: Set up Rust Environment for macOS
      run: |
        rustup target add x86_64-apple-darwin

    - name: List Rust Environment Version info
      run: |
        rustup --version
        cargo --version
        rustc --version

    - name: Build for macOS
      run: |
        cargo build --release --target x86_64-apple-darwin
        cp target/x86_64-apple-darwin/release/rust-quicktotp ./quicktotp-darwin-x86_64

    - name: Generate Changelog
      run: echo "# Release Notes" > changelog.txt  # Replace this with your actual changelog content

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          changelog.txt
          quicktotp-darwin-x86_64
        body_path: changelog.txt
        tag_name: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-msvc

    - name: Set release tag
      id: set_tag
      shell: powershell
      run: |
        $tag = git rev-parse --short=8 $env:GITHUB_SHA
        Set-Content -Path $env:GITHUB_ENV -Value "tag=$tag"

    # Windows-specific Rust Environment setup not required.

    - name: List Rust Environment Version info
      run: |
        rustup --version
        cargo --version
        rustc --version

    - name: Build for Windows x86-64
      run: |
        cargo build --release --target x86_64-pc-windows-msvc
        ls target/x86_64-pc-windows-msvc/release/
        cp target/x86_64-pc-windows-msvc/release/rust-quicktotp.exe ./quicktotp-windows-x86_64.exe

    - name: Generate Changelog
      run: echo "# Release Notes" > changelog.txt  # Replace this with your actual changelog content

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          changelog.txt
          quicktotp-windows-x86_64.exe
        body_path: changelog.txt
        tag_name: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
